version: '3'
services:
  prod:
    build: .
    ports:
      - "3050:3050"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
