name: Docker Deploy Workflow

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    name: Deploy Application with Docker Compose
    runs-on: self-hosted
    needs: build-and-test

    steps:
      - name: Stop Docker containers
        run: |
          cd /var/www/myapp/_work/rede-flex/rede-flex
          docker compose down
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          cd /var/www/myapp/_work/rede-flex/rede-flex
          git pull origin development
          docker compose up -d --build prod

#Saulo
# name: Docker Deploy Workflow

# on:
#   push:
#     branches:
#       - development

# jobs:
#   deploy:
#     name: Deploy Application with Docker Compose
#     runs-on: self-hosted

#     steps:
#       - name: Check out the code
#         uses: actions/checkout@v3

   
#       - name: Deploy with Docker Compose
#         run: |
#           cd /var/www/myapp/_work/rede-flex/rede-flex
#           git pull origin development
#           docker compose up -d --build prod


# name: CI/CD for Next.js

# on:
#   push:
#     branches:
#       - development
#   pull_request:
#     branches:
#       - development

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: "npm"

#       - name: Install Dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#   deploy:
#     name: Deploy CD
#     runs-on: self-hosted
#     needs: build-and-test # Depende do job de build-and-test

#     steps:
#       # Limpa o workspace antes de fazer o checkout
#       - name: Clean workspace
#         run: |
#           if [ -d "/var/www/myapp/_work/rede-flex/rede-flex" ]; then
#             sudo chmod -R 755 /var/www/myapp/_work/rede-flex/rede-flex
#             sudo rm -rf /var/www/myapp/_work/rede-flex/rede-flex
#           fi

#       # Faz o checkout do código
#       - name: Checkout Code
#         uses: actions/checkout@v3
#         with:
#           submodules: false # Evita problemas com submodules

#       # Deploy usando Docker Compose
#       - name: Deploy Docker Compose
#         run: |
#           cd /var/www/myapp/_work/rede-flex/rede-flex
#           git pull origin development
#           docker compose up -d --build prod




# name: CI/CD for Next.js

# on:
#   push:
#     branches:
#       - development
#   pull_request:
#     branches:
#       - development

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: "npm"

#       - name: Install Dependencies
#         run: npm install

#       - name: Build
#         run: npm run build
